package capabilities

// TableRowCount is the number of frozen REST↔MCP catalog rows
// (REST_ONLY health plus every PARITY_REQUIRED row).
const TableRowCount = 28

func catalog() []Capability {
	return []Capability{
		{
			ID: HealthLive, Title: "Health live", Version: VersionTag,
			Description: "Process liveness. Not an MCP tool.",
			Idempotent:  true, RESTOnly: true,
			REST: []RESTBinding{{Method: "GET", Path: "/v1/health/live"}},
		},
		{
			ID: HealthReady, Title: "Health ready", Version: VersionTag,
			Description: "Snapshot loaded and enabled listeners bound, or management off. Not an MCP tool.",
			Idempotent:  true, RESTOnly: true,
			REST: []RESTBinding{{Method: "GET", Path: "/v1/health/ready"}},
		},
		{
			ID: VersionGet, Title: "Version", Version: VersionTag,
			Description:    "Build and protocol versions.",
			RequiredScopes: []string{ScopeNetconfRead}, Idempotent: true,
			OutputSchema:   &SchemaRef{Name: "Version"},
			REST:           []RESTBinding{{Method: "GET", Path: "/v1/version"}},
			MCP:            &MCPBinding{Tools: []string{"netconf_version_get"}},
			ServiceMethods: []string{"Version"},
		},
		{
			ID: CapabilitiesGet, Title: "Capabilities", Version: VersionTag,
			Description:    "Capability list and protocol metadata.",
			RequiredScopes: []string{ScopeNetconfRead}, Idempotent: true,
			OutputSchema:   &SchemaRef{Name: "CapabilityView"},
			REST:           []RESTBinding{{Method: "GET", Path: "/v1/capabilities"}},
			MCP:            &MCPBinding{Tools: []string{"netconf_capabilities_get"}},
			ServiceMethods: []string{"Capabilities"},
		},
		{
			ID: StatusGet, Title: "Agent status", Version: VersionTag,
			Description:    "Listeners, revision, and ready.",
			RequiredScopes: []string{ScopeNetconfRead}, Idempotent: true,
			OutputSchema:   &SchemaRef{Name: "Status"},
			REST:           []RESTBinding{{Method: "GET", Path: "/v1/status"}},
			MCP:            &MCPBinding{Tools: []string{"netconf_status_get"}},
			ServiceMethods: []string{"Status"},
		},
		{
			ID: SchemaGet, Title: "Config schema", Version: VersionTag,
			Description:    "Published v1alpha1 config JSON Schema.",
			RequiredScopes: []string{ScopeNetconfRead}, Idempotent: true,
			REST:           []RESTBinding{{Method: "GET", Path: "/v1/schema/config"}},
			MCP:            &MCPBinding{Tools: []string{"netconf_schema_get"}, Resources: []string{"labnetconf://schema/config"}},
			ServiceMethods: []string{"Schema"},
		},
		{
			ID: FeaturesList, Title: "Features", Version: VersionTag,
			Description:    "Frozen live vs reset-only catalog.",
			RequiredScopes: []string{ScopeNetconfRead}, Idempotent: true,
			OutputSchema:   &SchemaRef{Name: "FeatureList"},
			REST:           []RESTBinding{{Method: "GET", Path: "/v1/features"}},
			MCP:            &MCPBinding{Tools: []string{"netconf_features_list"}},
			ServiceMethods: []string{"Features"},
		},
		{
			ID: StateGet, Title: "Get state", Version: VersionTag,
			Description:    "Redacted spec plus revision metadata.",
			RequiredScopes: []string{ScopeNetconfRead}, Idempotent: true,
			OutputSchema:   &SchemaRef{Name: "StateView"},
			REST:           []RESTBinding{{Method: "GET", Path: "/v1/state"}},
			MCP:            &MCPBinding{Tools: []string{"netconf_state_get"}, Resources: []string{"labnetconf://state"}},
			ServiceMethods: []string{"State"},
		},
		{
			ID: StateValidate, Title: "Validate", Version: VersionTag,
			Description:    "Validate a candidate document without writing.",
			RequiredScopes: []string{ScopeNetconfAdmin}, Idempotent: true,
			REST:           []RESTBinding{{Method: "POST", Path: "/v1/state:validate"}},
			MCP:            &MCPBinding{Tools: []string{"netconf_state_validate"}},
			ServiceMethods: []string{"ValidateState"},
		},
		{
			ID: StateExport, Title: "Export", Version: VersionTag,
			Description:    "Canonical desired-state YAML. Secret bytes are absent.",
			RequiredScopes: []string{ScopeNetconfAdmin}, Idempotent: true,
			REST:           []RESTBinding{{Method: "GET", Path: "/v1/state:export"}},
			MCP:            &MCPBinding{Tools: []string{"netconf_state_export"}},
			ServiceMethods: []string{"ExportState"},
		},
		{
			ID: StateReset, Title: "Reset", Version: VersionTag,
			Description:    "Reread the bootstrap mount, restore trees, and wipe notifications. Never writes the file.",
			RequiredScopes: []string{ScopeNetconfAdmin}, Mutating: true,
			REST:           []RESTBinding{{Method: "POST", Path: "/v1/state:reset"}},
			MCP:            &MCPBinding{Tools: []string{"netconf_state_reset"}},
			ServiceMethods: []string{"Reset"},
		},
		{
			ID: ChangesPlan, Title: "Plan", Version: VersionTag,
			Description:    "Dry-run operations against the active snapshot.",
			RequiredScopes: []string{ScopeNetconfAdmin}, Idempotent: true,
			InputSchema:    &SchemaRef{Name: "ChangeIn"},
			OutputSchema:   &SchemaRef{Name: "Plan"},
			REST:           []RESTBinding{{Method: "POST", Path: "/v1/changes:plan"}},
			MCP:            &MCPBinding{Tools: []string{"netconf_change_plan"}},
			ServiceMethods: []string{"Plan"},
		},
		{
			ID: ChangesApply, Title: "Apply", Version: VersionTag,
			Description:    "Apply operations. expectedRevision and Idempotency-Key are required.",
			RequiredScopes: []string{ScopeNetconfAdmin}, Mutating: true, Idempotent: true,
			InputSchema:    &SchemaRef{Name: "ChangeIn"},
			OutputSchema:   &SchemaRef{Name: "ApplyResult"},
			REST:           []RESTBinding{{Method: "POST", Path: "/v1/changes:apply"}},
			MCP:            &MCPBinding{Tools: []string{"netconf_change_apply"}},
			ServiceMethods: []string{"Apply"},
		},
		{
			ID: ProfilesList, Title: "List profiles", Version: VersionTag,
			Description:    "Named device profiles.",
			RequiredScopes: []string{ScopeNetconfRead}, Idempotent: true,
			REST:           []RESTBinding{{Method: "GET", Path: "/v1/profiles"}},
			MCP:            &MCPBinding{Tools: []string{"netconf_profiles_list"}},
			ServiceMethods: []string{"ListProfiles"},
		},
		{
			ID: ProfilesGet, Title: "Get profile", Version: VersionTag,
			Description:    "One profile by name.",
			RequiredScopes: []string{ScopeNetconfRead}, Idempotent: true,
			REST:           []RESTBinding{{Method: "GET", Path: "/v1/profiles/{name}"}},
			MCP:            &MCPBinding{Tools: []string{"netconf_profile_get"}, Resources: []string{"labnetconf://profiles/{name}"}},
			ServiceMethods: []string{"GetProfile"},
		},
		{
			ID: UsersList, Title: "List users", Version: VersionTag,
			Description:    "Data-plane users. Secret file contents are omitted.",
			RequiredScopes: []string{ScopeNetconfRead}, Idempotent: true,
			REST:           []RESTBinding{{Method: "GET", Path: "/v1/users"}},
			MCP:            &MCPBinding{Tools: []string{"netconf_users_list"}},
			ServiceMethods: []string{"ListUsers"},
		},
		{
			ID: DatastoreGet, Title: "Get datastore", Version: VersionTag,
			Description:    "Instance tree JSON for a profile store (running, candidate, or startup).",
			RequiredScopes: []string{ScopeNetconfRead}, Idempotent: true,
			REST:           []RESTBinding{{Method: "GET", Path: "/v1/datastores/{profile}/{store}"}},
			MCP:            &MCPBinding{Tools: []string{"netconf_datastore_get"}, Resources: []string{"labnetconf://datastores/{profile}/{store}"}},
			ServiceMethods: []string{"GetDatastore"},
		},
		{
			ID: DatastoreSet, Title: "Set datastore", Version: VersionTag,
			Description:    "Overlay/tree write on a profile store. Tester helper; same engine as edit-config.",
			RequiredScopes: []string{ScopeNetconfWrite}, Mutating: true,
			REST:           []RESTBinding{{Method: "POST", Path: "/v1/datastores/{profile}/{store}:set"}},
			MCP:            &MCPBinding{Tools: []string{"netconf_datastore_set"}},
			ServiceMethods: []string{"SetDatastore"},
		},
		{
			ID: DatastoreCommit, Title: "Commit", Version: VersionTag,
			Description:    "Publish candidate to running for a profile.",
			RequiredScopes: []string{ScopeNetconfWrite}, Mutating: true,
			REST:           []RESTBinding{{Method: "POST", Path: "/v1/datastores/{profile}:commit"}},
			MCP:            &MCPBinding{Tools: []string{"netconf_datastore_commit"}},
			ServiceMethods: []string{"Commit"},
		},
		{
			ID: DatastoreDiscard, Title: "Discard", Version: VersionTag,
			Description:    "Restore candidate from running for a profile.",
			RequiredScopes: []string{ScopeNetconfWrite}, Mutating: true,
			REST:           []RESTBinding{{Method: "POST", Path: "/v1/datastores/{profile}:discard"}},
			MCP:            &MCPBinding{Tools: []string{"netconf_datastore_discard"}},
			ServiceMethods: []string{"Discard"},
		},
		{
			ID: SessionsList, Title: "List sessions", Version: VersionTag,
			Description:    "NETCONF SSH and RESTCONF HTTP sessions.",
			RequiredScopes: []string{ScopeNetconfRead}, Idempotent: true,
			REST:           []RESTBinding{{Method: "GET", Path: "/v1/sessions"}},
			MCP:            &MCPBinding{Tools: []string{"netconf_sessions_list"}},
			ServiceMethods: []string{"ListSessions"},
		},
		{
			ID: SessionKill, Title: "Kill session", Version: VersionTag,
			Description:    "Drop one NETCONF or RESTCONF session by id.",
			RequiredScopes: []string{ScopeNetconfAdmin}, Mutating: true,
			REST:           []RESTBinding{{Method: "POST", Path: "/v1/sessions/{id}:kill"}},
			MCP:            &MCPBinding{Tools: []string{"netconf_session_kill"}},
			ServiceMethods: []string{"KillSession"},
		},
		{
			ID: NotificationsList, Title: "List notifications", Version: VersionTag,
			Description:    "In-process RFC 5277 config-change records.",
			RequiredScopes: []string{ScopeNetconfRead}, Idempotent: true,
			REST:           []RESTBinding{{Method: "GET", Path: "/v1/notifications"}},
			MCP:            &MCPBinding{Tools: []string{"netconf_notifications_list"}},
			ServiceMethods: []string{"ListNotifications"},
		},
		{
			ID: NotificationsGet, Title: "Get notification", Version: VersionTag,
			Description:    "One notification by id.",
			RequiredScopes: []string{ScopeNetconfRead}, Idempotent: true,
			REST:           []RESTBinding{{Method: "GET", Path: "/v1/notifications/{id}"}},
			MCP:            &MCPBinding{Tools: []string{"netconf_notification_get"}, Resources: []string{"labnetconf://notifications/{id}"}},
			ServiceMethods: []string{"GetNotification"},
		},
		{
			ID: NotificationsWait, Title: "Wait for notification", Version: VersionTag,
			Description:    "Block until a matching config-change record, timeout, or wipe.",
			RequiredScopes: []string{ScopeNetconfRead}, Idempotent: true,
			REST:           []RESTBinding{{Method: "POST", Path: "/v1/notifications:wait"}},
			MCP:            &MCPBinding{Tools: []string{"netconf_notifications_wait"}},
			ServiceMethods: []string{"WaitNotification"},
		},
		{
			ID: NotificationsClear, Title: "Clear notifications", Version: VersionTag,
			Description:    "Drop stored notifications without resetting bootstrap.",
			RequiredScopes: []string{ScopeNetconfWrite}, Mutating: true,
			REST:           []RESTBinding{{Method: "POST", Path: "/v1/notifications:clear"}},
			MCP:            &MCPBinding{Tools: []string{"netconf_notifications_clear"}},
			ServiceMethods: []string{"ClearNotifications"},
		},
		{
			ID: PreviewGet, Title: "Preview get", Version: VersionTag,
			Description:    "Evaluate a user + path against running without opening SSH.",
			RequiredScopes: []string{ScopeNetconfRead}, Idempotent: true,
			REST:           []RESTBinding{{Method: "GET", Path: "/v1/preview/get"}},
			MCP:            &MCPBinding{Tools: []string{"netconf_preview_get"}},
			ServiceMethods: []string{"PreviewGet"},
		},
		{
			ID: AuditQuery, Title: "Audit query", Version: VersionTag,
			Description:    "Recent in-memory mutation events.",
			RequiredScopes: []string{ScopeNetconfAuditRead}, Idempotent: true,
			REST:           []RESTBinding{{Method: "GET", Path: "/v1/audit"}},
			MCP:            &MCPBinding{Tools: []string{"netconf_audit_query"}},
			ServiceMethods: []string{"QueryAudit"},
		},
	}
}
